# Generated by Django 4.2.4 on 2023-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
